insert into appliances values (default, 'Air fryer');
insert into appliances values (default, 'Bachelor griller');
insert into appliances values (default, 'Barbecue grill');
insert into appliances values (default, 'Beehive oven');
insert into appliances values (default, 'Brasero (heater)');
insert into appliances values (default, 'Brazier');
insert into appliances values (default, 'Bread machine');
insert into appliances values (default, 'Burjiko');
insert into appliances values (default, 'Butane torch');
insert into appliances values (default, 'Chapati maker');
insert into appliances values (default, 'Cheesemelter');
insert into appliances values (default, 'Chocolatera');
insert into appliances values (default, 'Chorkor oven');
insert into appliances values (default, 'Clome oven');
insert into appliances values (default, 'Comal (cookware)');
insert into appliances values (default, 'Combi steamer');
insert into appliances values (default, 'Communal oven');
insert into appliances values (default, 'Convection microwave');
insert into appliances values (default, 'Convection oven');
insert into appliances values (default, 'Corn roaster');
insert into appliances values (default, 'Crepe maker');
insert into appliances values (default, 'Deep fryer');
insert into appliances values (default, 'Earth oven');
insert into appliances values (default, 'Electric cooker');
insert into appliances values (default, 'Energy regulator');
insert into appliances values (default, 'Espresso machine');
insert into appliances values (default, 'Field kitchen');
insert into appliances values (default, 'Fire pot');
insert into appliances values (default, 'Flattop grill');
insert into appliances values (default, 'Food steamer');
insert into appliances values (default, 'Fufu Machine');
insert into appliances values (default, 'Griddle');
insert into appliances values (default, 'Halogen oven');
insert into appliances values (default, 'Haybox');
insert into appliances values (default, 'Hibachi');
insert into appliances values (default, 'Horno');
insert into appliances values (default, 'Hot box (appliance)');
insert into appliances values (default, 'Hot plate');
insert into appliances values (default, 'Instant Pot');
insert into appliances values (default, 'Kamado');
insert into appliances values (default, 'Kitchener range');
insert into appliances values (default, 'Kujiejun');
insert into appliances values (default, 'Kyoto box');
insert into appliances values (default, 'Makiyakinabe');
insert into appliances values (default, 'Masonry oven');
insert into appliances values (default, 'Mess kit');
insert into appliances values (default, 'Microwave oven');
insert into appliances values (default, 'Multicooker');
insert into appliances values (default, 'Oven');
insert into appliances values (default, 'Pancake machine');
insert into appliances values (default, 'Panini sandwich grill');
insert into appliances values (default, 'Popcorn maker');
insert into appliances values (default, 'Pressure cooker');
insert into appliances values (default, 'Pressure fryer');
insert into appliances values (default, 'Reflector oven');
insert into appliances values (default, 'Remoska');
insert into appliances values (default, 'Rice cooker');
insert into appliances values (default, 'Rice polisher');
insert into appliances values (default, 'Roasting jack');
insert into appliances values (default, 'Rocket mass heater');
insert into appliances values (default, 'Rotimatic');
insert into appliances values (default, 'Rotisserie');
insert into appliances values (default, 'Russian oven');
insert into appliances values (default, 'Sabbath mode');
insert into appliances values (default, 'Salamander broiler');
insert into appliances values (default, 'Samovar');
insert into appliances values (default, 'Sandwich toaster');
insert into appliances values (default, 'Self-cleaning oven');
insert into appliances values (default, 'Shichirin');
insert into appliances values (default, 'Slow cooker');
insert into appliances values (default, 'Solar cooker');
insert into appliances values (default, 'Sous-vide cooker');
insert into appliances values (default, 'Soy milk maker');
insert into appliances values (default, 'Stove');
insert into appliances values (default, 'Susceptor');
insert into appliances values (default, 'Tabun oven');
insert into appliances values (default, 'Tandoor');
insert into appliances values (default, 'Tangia');
insert into appliances values (default, 'Thermal immersion circulator');
insert into appliances values (default, 'Toaster and toaster ovens');
insert into appliances values (default, 'Turkey fryer');
insert into appliances values (default, 'Vacuum fryer');
insert into appliances values (default, 'Waffle iron');
insert into appliances values (default, 'Wet grinder');
insert into appliances values (default, 'Wood-fired oven');
